//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\patri\Documents\GitHub\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 29 Apr 2022 - 14:28:32. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E01980200),
               .INIT_01             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_02             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_03             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_04             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_05             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_06             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_07             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_08             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_09             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0A             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0B             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0C             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0D             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0E             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_0F             (256'h9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_10             (256'h03030303008500000300FF9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E9E),
               .INIT_11             (256'h9E03619E03209E03799E03619E036C9E03509E030C0303030303030303030303),
               .INIT_12             (256'hA3009E03209E033A9E03659E03679E03619E03739E03739E03659E034D9E0320),
               .INIT_13             (256'h00859E03459E03539E03559E03419E03509E030D9E030A9EAF04AC03A902A601),
               .INIT_14             (256'h030303030303030303030301850100858201180091017F01090A007E0000850C),
               .INIT_15             (256'h659E034D9E03209E03619E03209E03799E03619E036C9E03509E030C03030303),
               .INIT_16             (256'h04AC03A902A601A3009E03209E033A9E03659E03679E03619E03739E03739E03),
               .INIT_17             (256'h0100859E03479E034E9E03499E03599E03419E034C9E03509E030D9E030A9EAF),
               .INIT_18             (256'h9E034F9E03449E03209E03459E03479E03419E03539E03539E03459E034D01A2),
               .INIT_19             (256'h03549E03539E03499E03589E03459E03209E03549E03279E034E9E03539E0345),
               .INIT_1A             (256'h03449E03209E03459E03479E03419E03539E03539E03459E034D01360100A29E),
               .INIT_1B             (256'h539E03499E03589E03459E03209E03549E03279E034E9E03539E03459E034F9E),
               .INIT_1C             (256'h04007E310001007E3100007E31000100860B01008501FE000B00369E03549E03),
               .INIT_1D             (256'h034D9E03459E034DA26801008C01009505009000009EFF990009080706007E31),
               .INIT_1E             (256'h009E030D9E030A9E034C9E034C9E03559E03469E03209E03599E03529E034F9E),
               .INIT_1F             (256'hD2310400D2310100D2310000D2310100E000E401B8010C000005000000050100),
               .INIT_20             (256'h0B00140C0B03001433010F0000E801680100F404F000FCFFF8000C0908070600),
               .INIT_21             (256'h0032FF2D000908070600A8310400A831000100A8310000A83100010019014200),
               .INIT_22             (256'h01001731040102004C6801004901680109070600330B043668011E0100290424),
               .INIT_23             (256'h03036C04006801006415580068FF5E0009070600173114001731000017310401),
               .INIT_24             (256'h619E03209E03799E03619E036C9E03509E030C03030303030303030303030303),
               .INIT_25             (256'h9E03209E033A9E03659E03679E03619E03739E03739E03659E034D9E03209E03),
               .INIT_26             (256'h0303030303030303030303030303A29E030D9E030A9EAF04AC03A902A601A300),
               .INIT_27             (256'h4D9E03209E03619E03209E03649E03729E036F9E03639E03659E03529E030C03),
               .INIT_28             (256'h9E03539E030D9E030A9E033F9E03659E03679E03619E03739E03739E03659E03),
               .INIT_29             (256'h03549E03209E034E9E03549E03429E03209E03549E03439E03459E034C9E0345),
               .INIT_2A             (256'h469E030D9E030A9E03649E03729E036F9E03639E03659E03529E03209E036F9E),
               .INIT_2B             (256'h9E030C009EAF04AC03A902A601A3009E03209E033A9E03659E036C9E03699E03),
               .INIT_2C             (256'h033F9E036C9E036C9E03419E03209E03659E03749E03659E036C9E03659E0344),
               .INIT_2D             (256'h9E03659E03449E030C0303030303030303030303030303034C9E030D9E030A9E),
               .INIT_2E             (256'h03739E03739E03659E034D9E03209E03619E03209E03659E03749E03659E036C),
               .INIT_2F             (256'h3A9E03659E036C9E03699E03469E030D9E030A9E033F9E03659E03679E03619E),
               .INIT_30             (256'h030303030303030303369E030D9E030A9EAF04AC03A902A601A3009E03209E03),
               .INIT_31             (256'h03209E033A9E03659E036D9E03759E036C9E036F9E03569E030C030303030303),
               .INIT_32             (256'h9EDC0ED60DD00CCA0BC40ABE09BB08B807B506B205AF04AC03A902A601A3009E),
               .INIT_33             (256'h003331010017047D03A802D2017E0000909E030C00330B006C009E030D9E030A),
               .INIT_34             (256'h05008B6B01007FFF007B00008705008300080706003331040033310100333100),
               .INIT_35             (256'h0331000339000338000337000336000335000334000333000332000331009E01),
               .INIT_36             (256'h359E03310003349E03310003339E03310003329E03310003319E03310003309E),
               .INIT_37             (256'h0303030303030303330108030303030303030303030303030303330108000003),
               .INIT_38             (256'h0303030333010803030303030303030303030303030333010803030303030303),
               .INIT_39             (256'h3301080303030303030303030303030303033301080303030303030303030303),
               .INIT_3A             (256'h0303030303030303030303030303330108030303030303030303030303030303),
               .INIT_3B             (256'h0303030303030303030333010803030303030303030303030303030333010803),
               .INIT_3C             (256'h035711010C9E030C330303030303030303030303030303033301080303030303),
               .INIT_3D             (256'h4D9E03209E036F9E03749E03209E03659E036D9E036F9E03639E036C9E03659E),
               .INIT_3E             (256'h9E03729E03659E03799E03619E036C9E03709E03619E03699E03649E03659E03),
               .INIT_3F             (256'h032E9E03349E03209E036E9E036F9E03699E03739E03729E03659E03569E0320),
               .INITP_00            (256'h000000000000000000000000000000000000000000000000000000000000000D),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h00000000AA80000000000000001444890000005540000000000000000A200000),
               .INITP_03            (256'h6666A8000000000000A9A7D194CA800000000000000000020000000000000001),
               .INITP_04            (256'h00000000000201550000000000000000180144469A0140422D3B5DA21004BBD4),
               .INITP_05            (256'h0000000000000000000000000000000002AA0000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000018104A33331410040000000000000000000002AA0),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h000000000A91EA001088ED030303030303030303030303030303030303030303),
               .INIT_11             (256'h0368080368080368080368080368080368080368080000000000000000000000),
               .INIT_12             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h00110368080368080368080368080368080368080368080383EC83EC83EC83EC),
               .INIT_14             (256'h00000000000000000000000A91EA001191E891E8B1EA91E8484800120A00116C),
               .INIT_15             (256'h0803680803680803680803680803680803680803680803680803680800000000),
               .INIT_16             (256'hEC83EC83EC83EC83EC0368080368080368080368080368080368080368080368),
               .INIT_17             (256'hEB00110368080368080368080368080368080368080368080368080368080383),
               .INIT_18             (256'h0368080368080368080368080368080368080368080368080368080368080B91),
               .INIT_19             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1A             (256'h68080368080368080368080368080368080368080368080368080B92EB001103),
               .INIT_1B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_1C             (256'h0C00B2EC0BCC00B2EC0C00B2EC0B8C001168080091E891E84800120368080368),
               .INIT_1D             (256'h68080368080368081193E90091E90091EC00A1E80091ECA1E84949484800B2EC),
               .INIT_1E             (256'h1203680803680803680803680803680803680803680803680803680803680803),
               .INIT_1F             (256'hB2EC0C00B2ECCC00B2EC0C00B2EC8C0091EC91EC91EA4A001268080012680800),
               .INIT_20             (256'h4800126C6808001294E848001291E993E90091ECA1E891ECA1E84A4949484800),
               .INIT_21             (256'hE892ECA2E84949484800B2EC0C00B2EC0BCC00B2EC0C00B2EC0B8C0092E891E8),
               .INIT_22             (256'h0F00B3EC6FCD0F001293E90082E893E8494848001468081293E992E90092ECA2),
               .INIT_23             (256'h0000126B0B93E90092EDA2E892EDA2E849484800B3EC0D00B3EC0D00B3EC6F8D),
               .INIT_24             (256'h0803680803680803680803680803680803680800000000000000000000000000),
               .INIT_25             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_26             (256'h0000000000000000000000000000110368080368080383EC83EC83EC83EC83EC),
               .INIT_27             (256'h0803680803680803680803680803680803680803680803680803680803680800),
               .INIT_28             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_29             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2A             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_2B             (256'h036808120383EC83EC83EC83EC83EC0368080368080368080368080368080368),
               .INIT_2C             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2D             (256'h0368080368080368080000000000000000000000000000001203680803680803),
               .INIT_2E             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2F             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_30             (256'h000000000000000000120368080368080383EC83EC83EC83EC83EC0368080368),
               .INIT_31             (256'h6808036808036808036808036808036808036808036808036808000000000000),
               .INIT_32             (256'h0383ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED03),
               .INIT_33             (256'h00B4EC8C0093E892E892E892E892E80C0003680800146808120D036808036808),
               .INIT_34             (256'h49001393E90093EC00A3E80093EC00A3E849484800B4EC0C00B4ECCC00B4EC0C),
               .INIT_35             (256'h68082868082868082868082868082868082868082868082868082868082893E9),
               .INIT_36             (256'h0803680828680803680828680803680828680803680828680803680828680803),
               .INIT_37             (256'h000000000000000094E84800000000000000000000000000000094E848002868),
               .INIT_38             (256'h0000000094E84800000000000000000000000000000094E84800000000000000),
               .INIT_39             (256'h94E84800000000000000000000000000000094E8480000000000000000000000),
               .INIT_3A             (256'h000000000000000000000000000094E848000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000094E84800000000000000000000000000000094E84800),
               .INIT_3C             (256'h680884E8080368081400000000000000000000000000000094E8480000000000),
               .INIT_3D             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_3E             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_3F             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'h3B6DB6DB556DB6DB6DB6DB6FFFE9AA1376DB6DAAB6DB6DB6DB6DB7FFF4DFFFFF),
               .INITP_03            (256'h8888A8CCEDB6DB6DB6C925022110CA3B6DB6DB6DB6DB6D93B6DB6DB6DB6DB6D9),
               .INITP_04            (256'h6DB6DB6DFFFFB6AADB6DB6DB6DB6DFFFF4AA088A28CA0DA55022110A398D2A80),
               .INITP_05            (256'h6DB6DB6DB6DB6DB6DB7FFFEDB6DB6DB6DD55B6DB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_06            (256'hFF9FFFE36DB6DB6DB6DB6DB632490444455466B6D5555555B6DB6DBFFFF6D55B),
               .INITP_07            (256'hB6DB6DB6DB6DB6DB6DB6DB6DA6FFFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE7F))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h9E03529E034F9E034D9E03459E034DE29E03399E03369E032E9E03309E03329E),
               .INIT_01             (256'h9E03659E034D11010C9E030C00009E034C9E034C9E03559E03469E03209E0359),
               .INIT_02             (256'h03569E03209E03729E03659E03799E03619E036C9E03709E03619E03699E0364),
               .INIT_03             (256'h309E03329E032E9E03349E03209E036E9E036F9E03699E03739E03729E03659E),
               .INIT_04             (256'h9E03209E03759E036E9E03659E034D9E030D9E030A9E03399E03369E032E9E03),
               .INIT_05             (256'h03319E030D9E030A9E033A9E03739E036E9E036F9E03699E03749E03709E034F),
               .INIT_06             (256'h4D9E03209E03619E03209E03799E03619E036C9E03509E03209E03299E032E9E),
               .INIT_07             (256'h9E032E9E03329E030D9E030A9E03659E03679E03619E03739E03739E03659E03),
               .INIT_08             (256'h03209E03619E03209E03649E03729E036F9E03639E03659E03529E03209E0329),
               .INIT_09             (256'h2E9E03339E030D9E030A9E03659E03679E03619E03739E03739E03659E034D9E),
               .INIT_0A             (256'h9E03619E03209E03659E03749E03659E036C9E03659E03449E03209E03299E03),
               .INIT_0B             (256'h03349E030D9E030A9E03659E03679E03619E03739E03739E03659E034D9E0320),
               .INIT_0C             (256'h619E03209E03659E03749E03659E036C9E03659E03449E03209E03299E032E9E),
               .INIT_0D             (256'h9E03659E03679E03619E03739E03739E03659E034D9E03209E036C9E036C9E03),
               .INIT_0E             (256'h03759E036C9E036F9E03569E03209E03299E032E9E03359E030D9E030A9E0373),
               .INIT_0F             (256'h0A9E036C9E036F9E03729E03749E036E9E036F9E03439E03209E03659E036D9E),
               .INIT_10             (256'h9E03539E03209E03749E036E9E03659E03729E03729E03759E03439E030D9E03),
               .INIT_11             (256'hA3009E03209E033A9E036E9E036F9E03699E03749E03639E03659E036C9E0365),
               .INIT_12             (256'h000000000000000000000000000000008B9E030D9E030A9EAF04AC03A902A601),
               .INIT_13             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_14             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h0000000000000000000000000000000000000000000000554000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h0368080368080368080368080368081303680803680803680803680803680803),
               .INIT_01             (256'h03680803680884E8080368080028036808036808036808036808036808036808),
               .INIT_02             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_03             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_04             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_05             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_06             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_07             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_08             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_09             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0A             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0B             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0C             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0D             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0E             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0F             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_10             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_11             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_12             (256'h00000000000000000000000000000000130368080368080383EC83EC83EC83EC),
               .INIT_13             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_14             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'hDB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DA676DB6DB6DDB6D),
               .INITP_01            (256'h6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_02            (256'h00000000000000000000000000000000000000000000EDAAB6DB6DB6DB6DB6DB),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
