//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\patri\Documents\GitHub\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 28 Apr 2022 - 18:09:53. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A01A00200),
               .INIT_01             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_02             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_03             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_04             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_05             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_06             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_07             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_08             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_09             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0A             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0B             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0C             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0D             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0E             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_0F             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_10             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_11             (256'h3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A3A),
               .INIT_12             (256'h03030303030303030300C00000233104002331010023310000233101000300FF),
               .INIT_13             (256'h034D3A03203A03613A03203A03793A03613A036C3A03503A030C030303030303),
               .INIT_14             (256'h03450242013F003A03203A033A3A03653A03673A03613A03733A03733A03653A),
               .INIT_15             (256'h230000C00C00C03A03453A03533A03553A03413A03503A030D3A030A3A4B0448),
               .INIT_16             (256'h0C03030303030303030303030303030301C00100C0BD015300CC01BA01090A00),
               .INIT_17             (256'h3A03733A03653A034D3A03203A03613A03203A03793A03613A036C3A03503A03),
               .INIT_18             (256'h3A030A3A4B044803450242013F003A03203A033A3A03653A03673A03613A0373),
               .INIT_19             (256'h3A034D01870100C03A03473A034E3A03493A03593A03413A034C3A03503A030D),
               .INIT_1A             (256'h03533A03453A034F3A03443A03203A03453A03473A03413A03533A03533A0345),
               .INIT_1B             (256'h000B00873A03543A03533A03493A03583A03453A03203A03543A03273A034E3A),
               .INIT_1C             (256'h050100870401008301004704004300004FFF4B0009080706007D0B0100C00139),
               .INIT_1D             (256'h000908070600743104007431010074310000743101009D00A10100BA050000BA),
               .INIT_1E             (256'h0706004A3104004A3101004A3100004A310100BAA501040100AE04AA00B6FFB2),
               .INIT_1F             (256'h010200F1040100EE01040109070600A00B04DD040100D104CD00D9FFD5000908),
               .INIT_20             (256'h0401000915FD000DFF030009070600B3311400B3310000B33104010100B33104),
               .INIT_21             (256'h03203A03793A03613A036C3A0350030303030303030303030303030303110400),
               .INIT_22             (256'h203A033A3A03653A03673A03613A03733A03733A03653A034D3A03203A03613A),
               .INIT_23             (256'h030303030303030303030303873A030D3A030A3A4B044803450242013F003A03),
               .INIT_24             (256'h03203A03613A03203A03643A03723A036F3A03633A03653A03523A030C030303),
               .INIT_25             (256'h533A030D3A030A3A033F3A03653A03673A03613A03733A03733A03653A034D3A),
               .INIT_26             (256'h3A03203A034E3A03543A03423A03203A03543A03433A03453A034C3A03453A03),
               .INIT_27             (256'h030D3A030A3A03643A03723A036F3A03633A03653A03523A03203A036F3A0354),
               .INIT_28             (256'h0CBA3A4B044803450242013F003A03203A033A3A03653A036C3A03693A03463A),
               .INIT_29             (256'h3A036C3A036C3A03413A03203A03653A03743A03653A036C3A03653A03443A03),
               .INIT_2A             (256'h653A03443A030C030303030303030303030303030303F13A030D3A030A3A033F),
               .INIT_2B             (256'h3A03733A03653A034D3A03203A03613A03203A03653A03743A03653A036C3A03),
               .INIT_2C             (256'h03653A036C3A03693A03463A030D3A030A3A033F3A03653A03673A03613A0373),
               .INIT_2D             (256'h03030303030303030303030303DD3A4B044803450242013F003A03203A033A3A),
               .INIT_2E             (256'h013F003A03203A033A3A03653A036D3A03753A036C3A036F3A03563A030C0303),
               .INIT_2F             (256'h0D3A030A3A780E720D6C0C660B600A5A095708540751064E054B044803450242),
               .INIT_30             (256'h00A0310000A0310100B3041F034A027401230000903A030C00A00B0011003A03),
               .INIT_31             (256'h31003A010500270701001BFF001700002305001F0008070600A0310400A03101),
               .INIT_32             (256'h0003303A03310003390003380003370003360003350003340003330003320003),
               .INIT_33             (256'h034D0003353A03310003343A03310003333A03310003323A03310003313A0331),
               .INIT_34             (256'h003A034C3A034C3A03553A03463A03203A03593A03523A034F3A034D3A03453A),
               .INIT_35             (256'h743A03203A03653A036D3A036F3A03633A036C3A03653A03577E010C3A030C00),
               .INIT_36             (256'h3A03613A036C3A03703A03613A03693A03643A03653A034D3A03203A036F3A03),
               .INIT_37             (256'h036E3A036F3A03693A03733A03723A03653A03563A03203A03723A03653A0379),
               .INIT_38             (256'h083A03083A030A3A03393A03363A032E3A03303A03323A032E3A03343A03203A),
               .INIT_39             (256'h03083A03083A03083A03083A03083A1303083A03083A03083A03083A03083A03),
               .INIT_3A             (256'h03083A03083A03083A03083A03083A03083A03083A1303083A1303083A03083A),
               .INIT_3B             (256'h083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A),
               .INIT_3C             (256'h3A03203A03753A036E3A03653A034D3A03083A03083A03083A03083A03083A03),
               .INIT_3D             (256'h03083A03083A030A3A033A3A03733A036E3A036F3A03693A03743A03703A034F),
               .INIT_3E             (256'h083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A),
               .INIT_3F             (256'h3A03613A03203A03793A03613A036C3A03503A03203A03293A032E3A03313A03),
               .INITP_00            (256'h0000000000000000000000000000000000000000000000000000000000000009),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h000000000000A22448000002AA00000000000000005333310000000000000000),
               .INITP_03            (256'h51282BBE9DDDD977D1999A9115105A4110000000000000000800000005540000),
               .INITP_04            (256'h00000000000000000000000000000000000805540000000000000003042999D7),
               .INITP_05            (256'h00000000000000000004AA80000000000000000000000200000000004AA80000),
               .INITP_06            (256'h00000000000000000000000000000000000000000000000018104A3333541004),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_11             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_12             (256'h0000000000000000000A91EA00B2EC0C00B2ECCC00B2EC0C00B2EC8C001088ED),
               .INIT_13             (256'h6808036808036808036808036808036808036808036808036808000000000000),
               .INIT_14             (256'hEC83EC83EC83EC03680803680803680803680803680803680803680803680803),
               .INIT_15             (256'h120A00116C00110368080368080368080368080368080368080368080383EC83),
               .INIT_16             (256'h080000000000000000000000000000000A91EA001191E891E8B1EA91E8484800),
               .INIT_17             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_18             (256'h0368080383EC83EC83EC83EC83EC036808036808036808036808036808036808),
               .INIT_19             (256'h0368080B91EB0011036808036808036808036808036808036808036808036808),
               .INIT_1A             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1B             (256'hE848001103680803680803680803680803680803680803680803680803680803),
               .INIT_1C             (256'h6808001193E90091E90091EC00A1E80091ECA1E849494848001168080091E891),
               .INIT_1D             (256'hE84949484800B2EC0C00B2ECCC00B2EC0C00B2EC8C0091EC91EC001168080011),
               .INIT_1E             (256'h484800B2EC0C00B2ECCC00B2EC0C00B2EC8C001191E993E90091ECA1E891ECA1),
               .INIT_1F             (256'hCD0F001193E90081E893E8494848001368081193E90091ECA1E891ECA1E84949),
               .INIT_20             (256'h93E90092EDA1E892EDA2E849484800B2EC0D00B2EC0D00B2EC6F8D0F00B2EC6F),
               .INIT_21             (256'h6808036808036808036808036808000000000000000000000000000000126B0B),
               .INIT_22             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_23             (256'h000000000000000000000000110368080368080383EC83EC83EC83EC83EC0368),
               .INIT_24             (256'h6808036808036808036808036808036808036808036808036808036808000000),
               .INIT_25             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_26             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_27             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_28             (256'h08110383EC83EC83EC83EC83EC03680803680803680803680803680803680803),
               .INIT_29             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2A             (256'h0803680803680800000000000000000000000000000011036808036808036808),
               .INIT_2B             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2C             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2D             (256'h00000000000000000000000000110383EC83EC83EC83EC83EC03680803680803),
               .INIT_2E             (256'hED83ED0368080368080368080368080368080368080368080368080368080000),
               .INIT_2F             (256'h080368080383ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83),
               .INIT_30             (256'h00B3EC0C00B3EC8C0092E892E892E892E892E80C0003680800136808120D0368),
               .INIT_31             (256'h082893E949001393E90093EC00A3E80093EC00A3E849484800B3EC0C00B3ECCC),
               .INIT_32             (256'h2868080368082868082868082868082868082868082868082868082868082868),
               .INIT_33             (256'h6808286808036808286808036808286808036808286808036808286808036808),
               .INIT_34             (256'h2803680803680803680803680803680803680803680803680803680803680803),
               .INIT_35             (256'h0803680803680803680803680803680803680803680803680883E80803680800),
               .INIT_36             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_37             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_38             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_39             (256'h6808036808036808036808036808037868080368080368080368080368080368),
               .INIT_3A             (256'h6808036808036808036808036808036808036808037868080378680803680803),
               .INIT_3B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_3C             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_3D             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_3E             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_3F             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'hDB6DB6DB7FFF4D509BB6DB6D55B6DB6DB6DB6DBFFFA44446FFFFFFFFFFFFFFFF),
               .INITP_03            (256'h1941B2A811111A55022222999924A0651DB6DB6DB6DB6DB6C9DB6DB6DAAB6DB6),
               .INITP_04            (256'hB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB7FFFEDAAB6DB6DB6DB6DBFFFE95411145),
               .INITP_05            (256'h6D5555555B6DB6DBFFFF556DB6DB6DB6DB6DB6DB6DFFFFB6DB6DB6DB7556DB6D),
               .INITP_06            (256'hB6DB6DB6DB6DB6DB6DB6DB4CEDB6DB6DB6DB6DB6DB6DB6DB632490444455466B),
               .INITP_07            (256'hDB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6EEDB6DBB6DB6DB6DB6D))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h03083A03083A030A3A03653A03673A03613A03733A03733A03653A034D3A0320),
               .INIT_01             (256'h083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A),
               .INIT_02             (256'h3A03523A03203A03293A032E3A03323A03083A03083A03083A03083A03083A03),
               .INIT_03             (256'h03733A03653A034D3A03203A03613A03203A03643A03723A036F3A03633A0365),
               .INIT_04             (256'h083A03083A03083A03083A03083A03083A030A3A03653A03673A03613A03733A),
               .INIT_05             (256'h3A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03),
               .INIT_06             (256'h036C3A03653A03443A03203A03293A032E3A03333A03083A03083A03083A0308),
               .INIT_07             (256'h613A03733A03733A03653A034D3A03203A03613A03203A03653A03743A03653A),
               .INIT_08             (256'h3A03083A03083A03083A03083A03083A03083A03083A030A3A03653A03673A03),
               .INIT_09             (256'h03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A0308),
               .INIT_0A             (256'h743A03653A036C3A03653A03443A03203A03293A032E3A03343A03083A03083A),
               .INIT_0B             (256'h3A03733A03733A03653A034D3A03203A036C3A036C3A03613A03203A03653A03),
               .INIT_0C             (256'h03083A03083A03083A03083A03083A03083A030A3A03733A03653A03673A0361),
               .INIT_0D             (256'h083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A),
               .INIT_0E             (256'h3A03203A03293A032E3A03353A03083A03083A03083A03083A03083A03083A03),
               .INIT_0F             (256'h03743A036E3A036F3A03433A03203A03653A036D3A03753A036C3A036F3A0356),
               .INIT_10             (256'h083A03083A03083A03083A03083A03083A03083A030A3A036C3A036F3A03723A),
               .INIT_11             (256'h3A03083A03083A03083A03083A03083A03083A03083A03083A03083A03083A03),
               .INIT_12             (256'h03653A03533A03203A03743A036E3A03653A03723A03723A03753A03433A0308),
               .INIT_13             (256'h42013F003A03203A033A3A036E3A036F3A03693A03743A03633A03653A036C3A),
               .INIT_14             (256'h000000000000000000000000000000000000000000000000273A4B0448034502),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h0000000000000000000000000000001550000000000000000000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_01             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_02             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_03             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_04             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_05             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_06             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_07             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_08             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_09             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0A             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0B             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0C             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0D             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0E             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0F             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_10             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_11             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_12             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h83EC83EC03680803680803680803680803680803680803680803680803680803),
               .INIT_14             (256'h000000000000000000000000000000000000000000000000130383EC83EC83EC),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_01            (256'hB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_02            (256'h000000000000000000000000000000EAADB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
