//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\patri\Documents\GitHub\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 29 Apr 2022 - 16:00:30. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB01E50200),
               .INIT_01             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_02             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_03             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_04             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_05             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_06             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_07             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_08             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_09             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0A             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0B             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0C             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0D             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0E             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_0F             (256'hEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_10             (256'h03030303008500000300FFEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEBEB),
               .INIT_11             (256'hEB0361EB0320EB0379EB0361EB036CEB0350EB030C0303030303030303030303),
               .INIT_12             (256'hF000EB0320EB033AEB0365EB0367EB0361EB0373EB0373EB0365EB034DEB0320),
               .INIT_13             (256'h0085EB0345EB0353EB0355EB0341EB0350EB030DEB030AEBFC04F903F602F301),
               .INIT_14             (256'h030303030303030303030301850100858201180091017F01090A00C90000850C),
               .INIT_15             (256'h65EB034DEB0320EB0361EB0320EB0379EB0361EB036CEB0350EB030C03030303),
               .INIT_16             (256'h04F903F602F301F000EB0320EB033AEB0365EB0367EB0361EB0373EB0373EB03),
               .INIT_17             (256'h010085EB0347EB034EEB0349EB0359EB0341EB034CEB0350EB030DEB030AEBFC),
               .INIT_18             (256'hEB034FEB0344EB0320EB0345EB0347EB0341EB0353EB0353EB0345EB034D01A2),
               .INIT_19             (256'h0354EB0353EB0349EB0358EB0345EB0320EB0354EB0327EB034EEB0353EB0345),
               .INIT_1A             (256'h0344EB0320EB0345EB0347EB0341EB0353EB0353EB0345EB034D01810100A2EB),
               .INIT_1B             (256'h53EB0349EB0358EB0345EB0320EB0354EB0327EB034EEB0353EB0345EB034FEB),
               .INIT_1C             (256'h0400C931000100C9310000C931000100860B01008501FE000B0081EB0354EB03),
               .INIT_1D             (256'h034DEB0345EB034DA2B501008C01009505009000009EFF99000908070600C931),
               .INIT_1E             (256'h4BEB030DEB030AEB034CEB034CEB0355EB0346EB0320EB0359EB0352EB034FEB),
               .INIT_1F             (256'hEB034CEB0341EB0320EB0345EB0347EB0341EB0353EB0353EB0345EB034D0100),
               .INIT_20             (256'h0354EB0353EB0349EB0358EB0345EB0320EB0359EB0344EB0341EB0345EB0352),
               .INIT_21             (256'h00001D3100010025002901E001B8010B0C0C004B0500004B0501004BEB0353EB),
               .INIT_22             (256'h004B2D01B501003E04390047FF42000C09080706001D3104001D310001001D31),
               .INIT_23             (256'h310400F531000100F5310000F531000100640142000B005F0C0B03005F80010F),
               .INIT_24             (256'h009401B50109070600800B0481B50169010074046F007DFF78000908070600F5),
               .INIT_25             (256'h00B3FFA90009070600643114006431000064310401010064310401020097B501),
               .INIT_26             (256'h036CEB0350EB030C030303030303030303030303030303B70400B50100AF15A3),
               .INIT_27             (256'h67EB0361EB0373EB0373EB0365EB034DEB0320EB0361EB0320EB0379EB0361EB),
               .INIT_28             (256'h030303A2EB030DEB030AEBFC04F903F602F301F000EB0320EB033AEB0365EB03),
               .INIT_29             (256'hEB0372EB036FEB0363EB0365EB0352EB030C0B02030303030303030303030303),
               .INIT_2A             (256'h0365EB0367EB0361EB0373EB0373EB0365EB034DEB0320EB0361EB0320EB0364),
               .INIT_2B             (256'h42EB0320EB0354EB0343EB0345EB034CEB0345EB0353EB030DEB030AEB033FEB),
               .INIT_2C             (256'hEB036FEB0363EB0365EB0352EB0320EB036FEB0354EB0320EB034EEB0354EB03),
               .INIT_2D             (256'hF000EB0320EB033AEB0365EB036CEB0369EB0346EB030DEB030AEB0364EB0372),
               .INIT_2E             (256'h20EB0365EB0374EB0365EB036CEB0365EB0344EB030C4BEBFC04F903F602F301),
               .INIT_2F             (256'h030303030303030303030397EB030DEB030AEB033FEB036CEB036CEB0341EB03),
               .INIT_30             (256'h20EB0361EB0320EB0365EB0374EB0365EB036CEB0365EB0344EB030C03030303),
               .INIT_31             (256'hEB030DEB030AEB033FEB0365EB0367EB0361EB0373EB0373EB0365EB034DEB03),
               .INIT_32             (256'hEB030AEBFC04F903F602F301F000EB0320EB033AEB0365EB036CEB0369EB0346),
               .INIT_33             (256'h75EB036CEB036FEB0356EB030C03030303030303030303030303030381EB030D),
               .INIT_34             (256'h080805070206FF05FC04F903F602F301F000EB0320EB033AEB0365EB036DEB03),
               .INIT_35             (256'hC9000090EB030C00800B00B700EB030DEB030AEB290E230D1D0C170B110A0B09),
               .INIT_36             (256'h0500D00008070600803104008031010080310000803101006404CA03F5021D01),
               .INIT_37             (256'h3600033500033400033300033200033100EB010500D8B80100CCFF00C80000D4),
               .INIT_38             (256'hEB0331000332EB0331000331EB0331000330EB03310003390003380003370003),
               .INIT_39             (256'h0303030303030303030303030380010800000335EB0331000334EB0331000333),
               .INIT_3A             (256'h0303030303030303038001080303030303030303030303030303038001080303),
               .INIT_3B             (256'h0303030303800108030303030303030303030303030303800108030303030303),
               .INIT_3C             (256'h0380010803030303030303030303030303030380010803030303030303030303),
               .INIT_3D             (256'h0303030303030303030303030303038001080303030303030303030303030303),
               .INIT_3E             (256'h0303030303030303030303800108030303030303030303030303030303800108),
               .INIT_3F             (256'hEB0365EB036DEB036FEB0363EB036CEB0365EB03575E010CEB030C8003030303),
               .INITP_00            (256'h000000000000000000000000000000000000000000000000000000000000000D),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h00000000AA80000000000000001444890000005540000000000000000A200000),
               .INITP_03            (256'h000000000000000000A9A7D194CA800000000000000000020000000000000001),
               .INITP_04            (256'h00000000000000C00A2234D00A021169DAED1080048AA76BB41D400000000000),
               .INITP_05            (256'h00000000000000554000000000000000000000000000000000000000100AA800),
               .INITP_06            (256'h000030209466662A20080AAAA800000000000000055400000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h000000000A91EA001088ED030303030303030303030303030303030303030303),
               .INIT_11             (256'h0368080368080368080368080368080368080368080000000000000000000000),
               .INIT_12             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h00110368080368080368080368080368080368080368080383EC83EC83EC83EC),
               .INIT_14             (256'h00000000000000000000000A91EA001191E891E8B1EA91E8484800120A00116C),
               .INIT_15             (256'h0803680803680803680803680803680803680803680803680803680800000000),
               .INIT_16             (256'hEC83EC83EC83EC83EC0368080368080368080368080368080368080368080368),
               .INIT_17             (256'hEB00110368080368080368080368080368080368080368080368080368080383),
               .INIT_18             (256'h0368080368080368080368080368080368080368080368080368080368080B91),
               .INIT_19             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1A             (256'h68080368080368080368080368080368080368080368080368080B92EB001103),
               .INIT_1B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_1C             (256'h0C00B2EC0BCC00B2EC0C00B2EC0B8C001168080091E891E84800120368080368),
               .INIT_1D             (256'h68080368080368081193E90091E90091EC00A1E80091ECA1E84949484800B2EC),
               .INIT_1E             (256'h1203680803680803680803680803680803680803680803680803680803680803),
               .INIT_1F             (256'h0368080368080368080368080368080368080368080368080368080368080B00),
               .INIT_20             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_21             (256'h0C00B2EC0B8C0092EC92EC91E991EA494A6C0012680800126808001203680803),
               .INIT_22             (256'h001292E993E90092ECA2E892ECA2E84A4949484800B2EC0C00B2EC0BCC00B2EC),
               .INIT_23             (256'hEC0C00B2EC0BCC00B2EC0C00B2EC0B8C0092E891E84800126C6808001294E848),
               .INIT_24             (256'h0082E893E8494848001468081293E992E90092ECA2E892ECA2E84949484800B2),
               .INIT_25             (256'hE892EDA2E849484800B3EC0D00B3EC0D00B3EC6F8D0F00B3EC6FCD0F001293E9),
               .INIT_26             (256'h6808036808036808000000000000000000000000000000126B0B93E90092EDA2),
               .INIT_27             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_28             (256'h000000110368080368080383EC83EC83EC83EC83EC0368080368080368080368),
               .INIT_29             (256'h0368080368080368080368080368080368086808000000000000000000000000),
               .INIT_2A             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_2C             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2D             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_2E             (256'h08036808036808036808036808036808036808036808120383EC83EC83EC83EC),
               .INIT_2F             (256'h0000000000000000000000120368080368080368080368080368080368080368),
               .INIT_30             (256'h0803680803680803680803680803680803680803680803680803680800000000),
               .INIT_31             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_32             (256'h0368080383EC83EC83EC83EC83EC036808036808036808036808036808036808),
               .INIT_33             (256'h0803680803680803680803680800000000000000000000000000000012036808),
               .INIT_34             (256'h83ED83ED83ED83ED83ED83ED83ED83ED83ED0368080368080368080368080368),
               .INIT_35             (256'h92E80C0003680800146808120D0368080368080383ED83ED83ED83ED83ED83ED),
               .INIT_36             (256'hEC00A3E849484800B4EC0C00B4ECCC00B4EC0C00B4EC8C0093E892E892E892E8),
               .INIT_37             (256'h082868082868082868082868082868082893E949001393E90093EC00A3E80093),
               .INIT_38             (256'h0368082868080368082868080368082868080368082868082868082868082868),
               .INIT_39             (256'h0000000000000000000000000094E84800286808036808286808036808286808),
               .INIT_3A             (256'h00000000000000000094E84800000000000000000000000000000094E8480000),
               .INIT_3B             (256'h000000000094E84800000000000000000000000000000094E848000000000000),
               .INIT_3C             (256'h0094E84800000000000000000000000000000094E84800000000000000000000),
               .INIT_3D             (256'h00000000000000000000000000000094E8480000000000000000000000000000),
               .INIT_3E             (256'h000000000000000000000094E84800000000000000000000000000000094E848),
               .INIT_3F             (256'h03680803680803680803680803680803680803680884E8080368081400000000),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'h3B6DB6DB556DB6DB6DB6DB6FFFE9AA1376DB6DAAB6DB6DB6DB6DB7FFF4DFFFFF),
               .INITP_03            (256'hDB6DB6D8EDB6DB6DB6C925022110CA3B6DB6DB6DB6DB6D93B6DB6DB6DB6DB6D9),
               .INITP_04            (256'h6DB6DB6DB6FFFFA550445146506D2A81108851CC695404422154599DB6DB6DB6),
               .INITP_05            (256'hFFFDB6DB6DB6DBAAB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DAFFFFDB556DB),
               .INITP_06            (256'h6DB6C649208888AA8CD6DAAAAAAAB6DB6DB7FFFEDAAB6DB6DB6DB6DB6DB6DB6F),
               .INITP_07            (256'hDB6DB4DFFFF3FFFCFFFF3FFFCFFFF3FFFCFFFF3FFFCFFFF3FFFC6DB6DB6DB6DB))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h036CEB0370EB0361EB0369EB0364EB0365EB034DEB0320EB036FEB0374EB0320),
               .INIT_01             (256'h6FEB0369EB0373EB0372EB0365EB0356EB0320EB0372EB0365EB0379EB0361EB),
               .INIT_02             (256'h034D2FEB0339EB0336EB032EEB0330EB0332EB032EEB0334EB0320EB036EEB03),
               .INIT_03             (256'h00EB034CEB034CEB0355EB0346EB0320EB0359EB0352EB034FEB034DEB0345EB),
               .INIT_04             (256'h79EB0361EB036CEB0370EB0361EB0369EB0364EB0365EB034D5E010CEB030C00),
               .INIT_05             (256'hEB036EEB036FEB0369EB0373EB0372EB0365EB0356EB0320EB0372EB0365EB03),
               .INIT_06             (256'h034DEB030DEB030AEB0339EB0336EB032EEB0330EB0332EB032EEB0334EB0320),
               .INIT_07             (256'h73EB036EEB036FEB0369EB0374EB0370EB034FEB0320EB0375EB036EEB0365EB),
               .INIT_08             (256'hEB0361EB036CEB0350EB0320EB0329EB032EEB0331EB030DEB030AEB033AEB03),
               .INIT_09             (256'h0365EB0367EB0361EB0373EB0373EB0365EB034DEB0320EB0361EB0320EB0379),
               .INIT_0A             (256'h72EB036FEB0363EB0365EB0352EB0320EB0329EB032EEB0332EB030DEB030AEB),
               .INIT_0B             (256'hEB0367EB0361EB0373EB0373EB0365EB034DEB0320EB0361EB0320EB0364EB03),
               .INIT_0C             (256'h0365EB036CEB0365EB0344EB0320EB0329EB032EEB0333EB030DEB030AEB0365),
               .INIT_0D             (256'h67EB0361EB0373EB0373EB0365EB034DEB0320EB0361EB0320EB0365EB0374EB),
               .INIT_0E             (256'hEB036CEB0365EB0344EB0320EB0329EB032EEB0334EB030DEB030AEB0365EB03),
               .INIT_0F             (256'h0373EB0365EB034DEB0320EB036CEB036CEB0361EB0320EB0365EB0374EB0365),
               .INIT_10             (256'h20EB0329EB032EEB0335EB030DEB030AEB0373EB0365EB0367EB0361EB0373EB),
               .INIT_11             (256'hEB036EEB036FEB0343EB0320EB0365EB036DEB0375EB036CEB036FEB0356EB03),
               .INIT_12             (256'h0365EB0372EB0372EB0375EB0343EB030DEB030AEB036CEB036FEB0372EB0374),
               .INIT_13             (256'h6FEB0369EB0374EB0363EB0365EB036CEB0365EB0353EB0320EB0374EB036EEB),
               .INIT_14             (256'h000000D8EB030DEB030AEBFC04F903F602F301F000EB0320EB033AEB036EEB03),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000000200000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h000000000000000000000000000AA80000000000000000000000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_01             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_02             (256'h6808130368080368080368080368080368080368080368080368080368080368),
               .INIT_03             (256'h2803680803680803680803680803680803680803680803680803680803680803),
               .INIT_04             (256'h0803680803680803680803680803680803680803680803680884E80803680800),
               .INIT_05             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_06             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_07             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_08             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_09             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0A             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0B             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0C             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0D             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0E             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0F             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_10             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_11             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_12             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_14             (256'h000000130368080368080383EC83EC83EC83EC83EC0368080368080368080368),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB4CEDB6DB6DBB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_01            (256'hB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_02            (256'h0000000000000000000000001DB556DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
