//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\patri\Documents\GitHub\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 04 May 2022 - 16:40:26. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F001EA0200),
               .INIT_01             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_02             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_03             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_04             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_05             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_06             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_07             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_08             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_09             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0A             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0B             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0C             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0D             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0E             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_0F             (256'hF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_10             (256'h03030303008500000300FFF0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0F0),
               .INIT_11             (256'hF00361F00320F00379F00361F0036CF00350F0030C0303030303030303030303),
               .INIT_12             (256'hF500F00320F0033AF00365F00367F00361F00373F00373F00365F0034DF00320),
               .INIT_13             (256'h0085F00345F00353F00355F00341F00350F0030DF0030AF00104FE03FB02F801),
               .INIT_14             (256'h03030303030303030303030303018501008582018F017F01090A00CE0000850C),
               .INIT_15             (256'hF00365F0034DF00320F00361F00320F00379F00361F0036CF00350F0030C0303),
               .INIT_16             (256'hF00104FE03FB02F801F500F00320F0033AF00365F00367F00361F00373F00373),
               .INIT_17             (256'h019C010085F00347F0034EF00349F00359F00341F0034CF00350F0030DF0030A),
               .INIT_18             (256'h0345F0034FF00344F00320F00345F00347F00341F00353F00353F00345F0034D),
               .INIT_19             (256'h9CF00354F00353F00349F00358F00345F00320F00354F00327F0034EF00353F0),
               .INIT_1A             (256'h4FF00344F00320F00345F00347F00341F00353F00353F00345F0034D01800100),
               .INIT_1B             (256'hF00353F00349F00358F00345F00320F00354F00327F0034EF00353F00345F003),
               .INIT_1C             (256'h08070600CE310400CE31000100CE310000CE31000100840B0100850080F00354),
               .INIT_1D             (256'hF0034FF0034DF00345F0034D9C0B01BA01008601008F05008A000098FF930009),
               .INIT_1E             (256'h034D01002BF0030DF0030AF0034CF0034CF00355F00346F00320F00359F00352),
               .INIT_1F             (256'h45F00352F0034CF00341F00320F00345F00347F00341F00353F00353F00345F0),
               .INIT_20             (256'hF00353F00354F00353F00349F00358F00345F00320F00359F00344F00341F003),
               .INIT_21             (256'h310000223100010021002B010C030303004A0500004ADC01B4010B0C0501002B),
               .INIT_22             (256'h0F004A2F01BA01003D04380046FF41000C090807060022310400223100010022),
               .INIT_23             (256'hFA310400FA31000100FA310000FA31000100630140000B005E0C0B03005E8501),
               .INIT_24             (256'h9501BA0109070600850B04800B03BA0168010073046E007CFF77000908070600),
               .INIT_25             (256'hAC0009070600693114006931000069310401010069310401020098BA0B040100),
               .INIT_26             (256'hF0030C030303030303030303030303030303BA0B050400BA0100B215A600B6FF),
               .INIT_27             (256'h0373F00373F00365F0034DF00320F00361F00320F00379F00361F0036CF00350),
               .INIT_28             (256'h030DF0030AF00104FE03FB02F801F500F00320F0033AF00365F00367F00361F0),
               .INIT_29             (256'h6FF00363F00365F00352F0030C0B020303030303030303030303030303039CF0),
               .INIT_2A             (256'hF00361F00373F00373F00365F0034DF00320F00361F00320F00364F00372F003),
               .INIT_2B             (256'h0354F00343F00345F0034CF00345F00353F0030DF0030AF0033FF00365F00367),
               .INIT_2C             (256'h63F00365F00352F00320F0036FF00354F00320F0034EF00354F00342F00320F0),
               .INIT_2D             (256'hF0033AF00365F0036CF00369F00346F0030DF0030AF00364F00372F0036FF003),
               .INIT_2E             (256'h0374F00365F0036CF00365F00344F0030C4AF00104FE03FB02F801F500F00320),
               .INIT_2F             (256'h03030303030398F0030DF0030AF0033FF0036CF0036CF00341F00320F00365F0),
               .INIT_30             (256'h0320F00365F00374F00365F0036CF00365F00344F0030C030303030303030303),
               .INIT_31             (256'h0AF0033FF00365F00367F00361F00373F00373F00365F0034DF00320F00361F0),
               .INIT_32             (256'h04FE03FB02F801F500F00320F0033AF00365F0036CF00369F00346F0030DF003),
               .INIT_33             (256'h036FF00356F0030C03030303030303030303030303030380F0030DF0030AF001),
               .INIT_34             (256'h0604050104FE03FB02F801F500F00320F0033AF00365F0036DF00375F0036CF0),
               .INIT_35             (256'h030C00850B00BA00F0030DF0030AF02E0E280D220C1C0B160A10090D080A0707),
               .INIT_36             (256'h070600853104008531010085310000853101006904CF03FA022201CE000090F0),
               .INIT_37             (256'h033400033300033200033100F0010500DDBD0100D1FF00CD0000D90500D50008),
               .INIT_38             (256'h32F00331000331F00331000330F0033100033900033800033700033600033500),
               .INIT_39             (256'h030303030303030385010800000335F00331000334F00331000333F003310003),
               .INIT_3A             (256'h0303030385010803030303030303030303030303030385010803030303030303),
               .INIT_3B             (256'h8501080303030303030303030303030303038501080303030303030303030303),
               .INIT_3C             (256'h0303030303030303030303030303850108030303030303030303030303030303),
               .INIT_3D             (256'h0303030303030303030385010803030303030303030303030303030385010803),
               .INIT_3E             (256'h0303030303038501080303030303030303030303030303038501080303030303),
               .INIT_3F             (256'h6DF0036FF00363F0036CF00365F0035763010CF0030C85030303030303030303),
               .INITP_00            (256'h000000000000000000000000000000000000000000000000000000000000000D),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h400000006AA000000000000000051489000000D540000000000000000A200000),
               .INITP_03            (256'h00000000000000000008A69F46532A0000000000000000008000000000000000),
               .INITP_04            (256'h00000000000006005111A680140108B4ED768840024553B5DA0803A000000000),
               .INITP_05            (256'h0000000000001AA8000000000000000000000000000000000000000203550000),
               .INITP_06            (256'h000604128CCCC544010155555000000000000001AA8000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h000000000A91EA001088ED030303030303030303030303030303030303030303),
               .INIT_11             (256'h0368080368080368080368080368080368080368080000000000000000000000),
               .INIT_12             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h00110368080368080368080368080368080368080368080383EC83EC83EC83EC),
               .INIT_14             (256'h000000000000000000000000000A91EA001191E891EA91E8484800120A00116C),
               .INIT_15             (256'h0368080368080368080368080368080368080368080368080368080368080000),
               .INIT_16             (256'h0383EC83EC83EC83EC83EC036808036808036808036808036808036808036808),
               .INIT_17             (256'h0B91EB0011036808036808036808036808036808036808036808036808036808),
               .INIT_18             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_19             (256'h1103680803680803680803680803680803680803680803680803680803680803),
               .INIT_1A             (256'h080368080368080368080368080368080368080368080368080368080B92EB00),
               .INIT_1B             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_1C             (256'h49484800B2EC0C00B2EC0BCC00B2EC0C00B2EC0B8C0011680800910012036808),
               .INIT_1D             (256'h03680803680803680803680811680893E90091E90091EC00A1E80091ECA1E849),
               .INIT_1E             (256'h68080B0012036808036808036808036808036808036808036808036808036808),
               .INIT_1F             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_20             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_21             (256'hEC0C00B2EC0B8C0092EC92EC6C00000000126808001291E991EA494A68080012),
               .INIT_22             (256'h48001292E993E90092ECA2E892ECA2E84A4949484800B2EC0C00B2EC0BCC00B2),
               .INIT_23             (256'hB2EC0C00B2EC0BCC00B2EC0C00B2EC0B8C0092E891E84800126C6808001294E8),
               .INIT_24             (256'h82E893E84948480014680812680893E992E90092ECA2E892ECA2E84949484800),
               .INIT_25             (256'hA2E849484800B3EC0D00B3EC0D00B3EC6F8D0F00B3EC6FCD0F0012936808E900),
               .INIT_26             (256'h0368080000000000000000000000000000001268086B0B93E90092EDA2E892ED),
               .INIT_27             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_28             (256'h68080368080383EC83EC83EC83EC83EC03680803680803680803680803680803),
               .INIT_29             (256'h0803680803680803680803680868080000000000000000000000000000001103),
               .INIT_2A             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2B             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2C             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_2D             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2E             (256'h6808036808036808036808036808036808120383EC83EC83EC83EC83EC036808),
               .INIT_2F             (256'h0000000000001203680803680803680803680803680803680803680803680803),
               .INIT_30             (256'h6808036808036808036808036808036808036808036808000000000000000000),
               .INIT_31             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_32             (256'hEC83EC83EC83EC83EC0368080368080368080368080368080368080368080368),
               .INIT_33             (256'h6808036808036808000000000000000000000000000000120368080368080383),
               .INIT_34             (256'hED83ED83ED83ED83ED83ED83ED03680803680803680803680803680803680803),
               .INIT_35             (256'h680800146808120D0368080368080383ED83ED83ED83ED83ED83ED83ED83ED83),
               .INIT_36             (256'h484800B4EC0C00B4ECCC00B4EC0C00B4EC8C0093E892E892E892E892E80C0003),
               .INIT_37             (256'h68082868082868082868082893E949001393E90093EC00A3E80093EC00A3E849),
               .INIT_38             (256'h0803680828680803680828680803680828680828680828680828680828680828),
               .INIT_39             (256'h000000000000000094E848002868080368082868080368082868080368082868),
               .INIT_3A             (256'h0000000094E84800000000000000000000000000000094E84800000000000000),
               .INIT_3B             (256'h94E84800000000000000000000000000000094E8480000000000000000000000),
               .INIT_3C             (256'h000000000000000000000000000094E848000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000094E84800000000000000000000000000000094E84800),
               .INIT_3E             (256'h00000000000094E84800000000000000000000000000000094E8480000000000),
               .INIT_3F             (256'h0803680803680803680803680803680884E80803680814000000000000000000),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'h4EDB6DB6D55B6DB6DB6DB6DBFFFA6A1376DB6DAAB6DB6DB6DB6DB7FFF4DFFFFF),
               .INITP_03            (256'h6DB6DB6D8EDB6DB6DB6D24940884432EDB6DB6DB6DB6DB64EDB6DB6DB6DB6DB6),
               .INITP_04            (256'hB6DB6DB6DFFFF52A82228A38A0DA9540884428E634AA022110AF6689DB6DB6DB),
               .INITP_05            (256'hFFB6DB6DB6DB7556DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB5FFFFB6AADB6D),
               .INITP_06            (256'hB6D8C924111115519ADB55555556DB6DB6FFFFDB556DB6DB6DB6DB6DB6DB6DFF),
               .INITP_07            (256'h6DB69BFFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE7FFF8DB6DB6DB6DB6D))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hF00361F00369F00364F00365F0034DF00320F0036FF00374F00320F00365F003),
               .INIT_01             (256'h0373F00372F00365F00356F00320F00372F00365F00379F00361F0036CF00370),
               .INIT_02             (256'h39F00336F0032EF00330F00332F0032EF00334F00320F0036EF0036FF00369F0),
               .INIT_03             (256'h034CF00355F00346F00320F00359F00352F0034FF0034DF00345F0034D34F003),
               .INIT_04             (256'hF00370F00361F00369F00364F00365F0034D63010CF0030C0B000000F0034CF0),
               .INIT_05             (256'h0369F00373F00372F00365F00356F00320F00372F00365F00379F00361F0036C),
               .INIT_06             (256'h0AF00339F00336F0032EF00330F00332F0032EF00334F00320F0036EF0036FF0),
               .INIT_07             (256'hF00369F00374F00370F0034FF00320F00375F0036EF00365F0034DF0030DF003),
               .INIT_08             (256'h0350F00320F00329F0032EF00331F0030DF0030AF0033AF00373F0036EF0036F),
               .INIT_09             (256'h61F00373F00373F00365F0034DF00320F00361F00320F00379F00361F0036CF0),
               .INIT_0A             (256'hF00365F00352F00320F00329F0032EF00332F0030DF0030AF00365F00367F003),
               .INIT_0B             (256'h0373F00373F00365F0034DF00320F00361F00320F00364F00372F0036FF00363),
               .INIT_0C             (256'h65F00344F00320F00329F0032EF00333F0030DF0030AF00365F00367F00361F0),
               .INIT_0D             (256'hF00373F00365F0034DF00320F00361F00320F00365F00374F00365F0036CF003),
               .INIT_0E             (256'h0344F00320F00329F0032EF00334F0030DF0030AF00365F00367F00361F00373),
               .INIT_0F             (256'h4DF00320F0036CF0036CF00361F00320F00365F00374F00365F0036CF00365F0),
               .INIT_10             (256'hF00335F0030DF0030AF00373F00365F00367F00361F00373F00373F00365F003),
               .INIT_11             (256'h0343F00320F00365F0036DF00375F0036CF0036FF00356F00320F00329F0032E),
               .INIT_12             (256'h72F00375F00343F0030DF0030AF0036CF0036FF00372F00374F0036EF0036FF0),
               .INIT_13             (256'hF00363F00365F0036CF00365F00353F00320F00374F0036EF00365F00372F003),
               .INIT_14             (256'hF0030AF00104FE03FB02F801F500F00320F0033AF0036EF0036FF00369F00374),
               .INIT_15             (256'h00000000000000000000000000000000000000000000000000000000DDF0030D),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000004000000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h0000000000000000000000000D54000000000000000000000000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_01             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_02             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_03             (256'h6808036808036808036808036808036808036808036808036808036808130368),
               .INIT_04             (256'h03680803680803680803680803680803680884E8080368086808002803680803),
               .INIT_05             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_06             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_07             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_08             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_09             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0A             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0B             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0C             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0D             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0E             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0F             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_10             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_11             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_12             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_13             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_14             (256'h0368080383EC83EC83EC83EC83EC036808036808036808036808036808036808),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000013036808),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'hDB6DB6DB6DB6DB6DB6DB6DB6DB6DA69DB6DB6DB76DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_01            (256'h6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_02            (256'h00000000000000000000000EDAAB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
