//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\patri\Documents\GitHub\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 02 May 2022 - 11:22:03. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE01E80200),
               .INIT_01             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_02             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_03             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_04             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_05             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_06             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_07             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_08             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_09             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0A             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0B             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0C             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0D             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0E             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_0F             (256'hEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_10             (256'h03030303008500000300FFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE),
               .INIT_11             (256'hEE0361EE0320EE0379EE0361EE036CEE0350EE030C0303030303030303030303),
               .INIT_12             (256'hF300EE0320EE033AEE0365EE0367EE0361EE0373EE0373EE0365EE034DEE0320),
               .INIT_13             (256'h0085EE0345EE0353EE0355EE0341EE0350EE030DEE030AEEFF04FC03F902F601),
               .INIT_14             (256'h030303030303030303030301850100858201180091017F01090A00CC0000850C),
               .INIT_15             (256'h65EE034DEE0320EE0361EE0320EE0379EE0361EE036CEE0350EE030C03030303),
               .INIT_16             (256'h04FC03F902F601F300EE0320EE033AEE0365EE0367EE0361EE0373EE0373EE03),
               .INIT_17             (256'h010085EE0347EE034EEE0349EE0359EE0341EE034CEE0350EE030DEE030AEEFF),
               .INIT_18             (256'hEE034FEE0344EE0320EE0345EE0347EE0341EE0353EE0353EE0345EE034D01A2),
               .INIT_19             (256'h0354EE0353EE0349EE0358EE0345EE0320EE0354EE0327EE034EEE0353EE0345),
               .INIT_1A             (256'h0344EE0320EE0345EE0347EE0341EE0353EE0353EE0345EE034D01840100A2EE),
               .INIT_1B             (256'h53EE0349EE0358EE0345EE0320EE0354EE0327EE034EEE0353EE0345EE034FEE),
               .INIT_1C             (256'h0400CC31000100CC310000CC31000100860B01008501FE000B0084EE0354EE03),
               .INIT_1D             (256'h034DEE0345EE034DA2B801008C01009505009000009EFF99000908070600CC31),
               .INIT_1E             (256'h2FEE030DEE030AEE034CEE034CEE0355EE0346EE0320EE0359EE0352EE034FEE),
               .INIT_1F             (256'hEE034CEE0341EE0320EE0345EE0347EE0341EE0353EE0353EE0345EE034D0100),
               .INIT_20             (256'h0354EE0353EE0349EE0358EE0345EE0320EE0359EE0344EE0341EE0345EE0352),
               .INIT_21             (256'h3100010025002F010C030303004E0500004EE001B8010B0C0501002FEE0353EE),
               .INIT_22             (256'h01B8010041043C004AFF45000C09080706002031040020310001002031000020),
               .INIT_23             (256'hF831000100F8310000F831000100670142000B00620C0B03006283010F004E33),
               .INIT_24             (256'hB80109070600830B0484B8016C01007704720080FF7B000908070600F8310400),
               .INIT_25             (256'hAC000907060067311400673100006731040101006731040102009AB801009701),
               .INIT_26             (256'h0350EE030C030303030303030303030303030303BA0400B80100B215A600B6FF),
               .INIT_27             (256'h61EE0373EE0373EE0365EE034DEE0320EE0361EE0320EE0379EE0361EE036CEE),
               .INIT_28             (256'hA2EE030DEE030AEEFF04FC03F902F601F300EE0320EE033AEE0365EE0367EE03),
               .INIT_29             (256'hEE036FEE0363EE0365EE0352EE030C0B02030303030303030303030303030303),
               .INIT_2A             (256'h0367EE0361EE0373EE0373EE0365EE034DEE0320EE0361EE0320EE0364EE0372),
               .INIT_2B             (256'h20EE0354EE0343EE0345EE034CEE0345EE0353EE030DEE030AEE033FEE0365EE),
               .INIT_2C             (256'hEE0363EE0365EE0352EE0320EE036FEE0354EE0320EE034EEE0354EE0342EE03),
               .INIT_2D             (256'h0320EE033AEE0365EE036CEE0369EE0346EE030DEE030AEE0364EE0372EE036F),
               .INIT_2E             (256'h65EE0374EE0365EE036CEE0365EE0344EE030C4EEEFF04FC03F902F601F300EE),
               .INIT_2F             (256'h03030303030303039AEE030DEE030AEE033FEE036CEE036CEE0341EE0320EE03),
               .INIT_30             (256'h61EE0320EE0365EE0374EE0365EE036CEE0365EE0344EE030C03030303030303),
               .INIT_31             (256'hEE030AEE033FEE0365EE0367EE0361EE0373EE0373EE0365EE034DEE0320EE03),
               .INIT_32             (256'hEEFF04FC03F902F601F300EE0320EE033AEE0365EE036CEE0369EE0346EE030D),
               .INIT_33             (256'h6CEE036FEE0356EE030C03030303030303030303030303030384EE030DEE030A),
               .INIT_34             (256'h0705060205FF04FC03F902F601F300EE0320EE033AEE0365EE036DEE0375EE03),
               .INIT_35             (256'h90EE030C00830B00BA00EE030DEE030AEE2C0E260D200C1A0B140A0E090B0808),
               .INIT_36             (256'h0008070600833104008331010083310000833101006704CD03F8022001CC0000),
               .INIT_37             (256'h3500033400033300033200033100EE010500DBBB0100CFFF00CB0000D70500D3),
               .INIT_38             (256'h000332EE0331000331EE0331000330EE03310003390003380003370003360003),
               .INIT_39             (256'h0303030303030303030383010800000335EE0331000334EE0331000333EE0331),
               .INIT_3A             (256'h0303030303038301080303030303030303030303030303038301080303030303),
               .INIT_3B             (256'h0303830108030303030303030303030303030303830108030303030303030303),
               .INIT_3C             (256'h0803030303030303030303030303030383010803030303030303030303030303),
               .INIT_3D             (256'h0303030303030303030303038301080303030303030303030303030303038301),
               .INIT_3E             (256'h0303030303030303830108030303030303030303030303030303830108030303),
               .INIT_3F             (256'hEE036DEE036FEE0363EE036CEE0365EE035761010CEE030C8303030303030303),
               .INITP_00            (256'h000000000000000000000000000000000000000000000000000000000000000D),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h00000000AA80000000000000001444890000005540000000000000000A200000),
               .INITP_03            (256'h000000000000000000A9A7D194CA800000000000000000020000000000000001),
               .INITP_04            (256'h00000000000006005111A68050108B4ED768840024553B5DA0803A0000000000),
               .INITP_05            (256'h00000000000002AA000000000000000000000000000000000000000080554000),
               .INITP_06            (256'h00018104A33331510040555550000000000000002AA000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h000000000A91EA001088ED030303030303030303030303030303030303030303),
               .INIT_11             (256'h0368080368080368080368080368080368080368080000000000000000000000),
               .INIT_12             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h00110368080368080368080368080368080368080368080383EC83EC83EC83EC),
               .INIT_14             (256'h00000000000000000000000A91EA001191E891E8B1EA91E8484800120A00116C),
               .INIT_15             (256'h0803680803680803680803680803680803680803680803680803680800000000),
               .INIT_16             (256'hEC83EC83EC83EC83EC0368080368080368080368080368080368080368080368),
               .INIT_17             (256'hEB00110368080368080368080368080368080368080368080368080368080383),
               .INIT_18             (256'h0368080368080368080368080368080368080368080368080368080368080B91),
               .INIT_19             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1A             (256'h68080368080368080368080368080368080368080368080368080B92EB001103),
               .INIT_1B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_1C             (256'h0C00B2EC0BCC00B2EC0C00B2EC0B8C001168080091E891E84800120368080368),
               .INIT_1D             (256'h68080368080368081193E90091E90091EC00A1E80091ECA1E84949484800B2EC),
               .INIT_1E             (256'h1203680803680803680803680803680803680803680803680803680803680803),
               .INIT_1F             (256'h0368080368080368080368080368080368080368080368080368080368080B00),
               .INIT_20             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_21             (256'hEC0B8C0092EC92EC6C00000000126808001291E991EA494A6808001203680803),
               .INIT_22             (256'hE993E90092ECA2E892ECA2E84A4949484800B2EC0C00B2EC0BCC00B2EC0C00B2),
               .INIT_23             (256'hB2EC0BCC00B2EC0C00B2EC0B8C0092E891E84800126C6808001294E848001292),
               .INIT_24             (256'h93E8494848001468081293E992E90092ECA2E892ECA2E84949484800B2EC0C00),
               .INIT_25             (256'hA2E849484800B3EC0D00B3EC0D00B3EC6F8D0F00B3EC6FCD0F001293E90082E8),
               .INIT_26             (256'h6808036808000000000000000000000000000000126B0B93E90092EDA2E892ED),
               .INIT_27             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_28             (256'h110368080368080383EC83EC83EC83EC83EC0368080368080368080368080368),
               .INIT_29             (256'h0368080368080368080368080368086808000000000000000000000000000000),
               .INIT_2A             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_2C             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2D             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2E             (256'h08036808036808036808036808036808036808120383EC83EC83EC83EC83EC03),
               .INIT_2F             (256'h0000000000000000120368080368080368080368080368080368080368080368),
               .INIT_30             (256'h0803680803680803680803680803680803680803680803680800000000000000),
               .INIT_31             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_32             (256'h0383EC83EC83EC83EC83EC036808036808036808036808036808036808036808),
               .INIT_33             (256'h0803680803680803680800000000000000000000000000000012036808036808),
               .INIT_34             (256'hED83ED83ED83ED83ED83ED83ED83ED0368080368080368080368080368080368),
               .INIT_35             (256'h0003680800146808120D0368080368080383ED83ED83ED83ED83ED83ED83ED83),
               .INIT_36             (256'hE849484800B4EC0C00B4ECCC00B4EC0C00B4EC8C0093E892E892E892E892E80C),
               .INIT_37             (256'h082868082868082868082868082893E949001393E90093EC00A3E80093EC00A3),
               .INIT_38             (256'h2868080368082868080368082868080368082868082868082868082868082868),
               .INIT_39             (256'h0000000000000000000094E84800286808036808286808036808286808036808),
               .INIT_3A             (256'h00000000000094E84800000000000000000000000000000094E8480000000000),
               .INIT_3B             (256'h000094E84800000000000000000000000000000094E848000000000000000000),
               .INIT_3C             (256'h4800000000000000000000000000000094E84800000000000000000000000000),
               .INIT_3D             (256'h00000000000000000000000094E84800000000000000000000000000000094E8),
               .INIT_3E             (256'h000000000000000094E84800000000000000000000000000000094E848000000),
               .INIT_3F             (256'h03680803680803680803680803680803680884E8080368081400000000000000),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'h3B6DB6DB556DB6DB6DB6DB6FFFE9AA1376DB6DAAB6DB6DB6DB6DB7FFF4DFFFFF),
               .INITP_03            (256'hDB6DB6D8EDB6DB6DB6C925022110CA3B6DB6DB6DB6DB6D93B6DB6DB6DB6DB6D9),
               .INITP_04            (256'h6DB6DB6DB7FFFD2A82228A328369540884428E634AA022110AF6689DB6DB6DB6),
               .INITP_05            (256'hFFEDB6DB6DB6DD55B6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D7FFFEDAAB6DB),
               .INITP_06            (256'h6DB632490444455466B6D5555555B6DB6DBFFFF6D55B6DB6DB6DB6DB6DB6DB7F),
               .INITP_07            (256'hDB6DA6FFFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE36DB6DB6DB6DB))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h0370EE0361EE0369EE0364EE0365EE034DEE0320EE036FEE0374EE0320EE0365),
               .INIT_01             (256'h69EE0373EE0372EE0365EE0356EE0320EE0372EE0365EE0379EE0361EE036CEE),
               .INIT_02             (256'hEE0339EE0336EE032EEE0330EE0332EE032EEE0334EE0320EE036EEE036FEE03),
               .INIT_03             (256'h4CEE034CEE0355EE0346EE0320EE0359EE0352EE034FEE034DEE0345EE034D32),
               .INIT_04             (256'h61EE036CEE0370EE0361EE0369EE0364EE0365EE034D61010CEE030C0000EE03),
               .INIT_05             (256'hEE036FEE0369EE0373EE0372EE0365EE0356EE0320EE0372EE0365EE0379EE03),
               .INIT_06             (256'h030DEE030AEE0339EE0336EE032EEE0330EE0332EE032EEE0334EE0320EE036E),
               .INIT_07             (256'h6EEE036FEE0369EE0374EE0370EE034FEE0320EE0375EE036EEE0365EE034DEE),
               .INIT_08             (256'hEE036CEE0350EE0320EE0329EE032EEE0331EE030DEE030AEE033AEE0373EE03),
               .INIT_09             (256'h0367EE0361EE0373EE0373EE0365EE034DEE0320EE0361EE0320EE0379EE0361),
               .INIT_0A             (256'h6FEE0363EE0365EE0352EE0320EE0329EE032EEE0332EE030DEE030AEE0365EE),
               .INIT_0B             (256'hEE0361EE0373EE0373EE0365EE034DEE0320EE0361EE0320EE0364EE0372EE03),
               .INIT_0C             (256'h036CEE0365EE0344EE0320EE0329EE032EEE0333EE030DEE030AEE0365EE0367),
               .INIT_0D             (256'h61EE0373EE0373EE0365EE034DEE0320EE0361EE0320EE0365EE0374EE0365EE),
               .INIT_0E             (256'hEE0365EE0344EE0320EE0329EE032EEE0334EE030DEE030AEE0365EE0367EE03),
               .INIT_0F             (256'h0365EE034DEE0320EE036CEE036CEE0361EE0320EE0365EE0374EE0365EE036C),
               .INIT_10             (256'h29EE032EEE0335EE030DEE030AEE0373EE0365EE0367EE0361EE0373EE0373EE),
               .INIT_11             (256'hEE036FEE0343EE0320EE0365EE036DEE0375EE036CEE036FEE0356EE0320EE03),
               .INIT_12             (256'h0372EE0372EE0375EE0343EE030DEE030AEE036CEE036FEE0372EE0374EE036E),
               .INIT_13             (256'h69EE0374EE0363EE0365EE036CEE0365EE0353EE0320EE0374EE036EEE0365EE),
               .INIT_14             (256'hDBEE030DEE030AEEFF04FC03F902F601F300EE0320EE033AEE036EEE036FEE03),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000001000000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h0000000000000000000000000055400000000000000000000000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_01             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_02             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_03             (256'h0803680803680803680803680803680803680803680803680803680803680813),
               .INIT_04             (256'h0803680803680803680803680803680803680803680884E80803680800280368),
               .INIT_05             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_06             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_07             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_08             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_09             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0A             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0B             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0C             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0D             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0E             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0F             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_10             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_11             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_12             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_14             (256'h130368080368080383EC83EC83EC83EC83EC0368080368080368080368080368),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h6DB6DB6DB6DB6DB6DB6DB6DB6DB6DA676DB6DB6DDB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_01            (256'hB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_02            (256'h000000000000000000000000EDAAB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
