//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2012, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 4K program for KCPSM6 in a Spartan-6 device using 
// 4 x RAMB18WER. It should be noted that a 4K program is not such a natural fit in
// a Spartan-6 device and the implementation also requires a small amount of logic 
// (9 x LUT6_2 and an FD) resulting in slightly lower performance compared with 
// memories for 1K and 2K programs.
//
//
// Program defined by 'C:\Users\thomasbivins\Desktop\Projects\CDA4203L-TeamLGSB\Final Project\picoblaze\program.psm'.
//
// Generated by KCPSM6 Assembler: 03 May 2022 - 22:45:13. 
//
// Assembler used ROM_form template: 26th November 2012
//
module program (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire        pipe_a11;
wire [35:0] data_in_a;
wire [35:0] data_out_a_ll;
wire [35:0] data_out_a_lh;
wire [35:0] data_out_a_hl;
wire [35:0] data_out_a_hh;
wire [13:0] address_b;
wire [35:0] data_in_b_ll;
wire [35:0] data_out_b_ll;
wire [35:0] data_in_b_lh;
wire [35:0] data_out_b_lh;
wire [35:0] data_in_b_hl;
wire [35:0] data_out_b_hl;
wire [35:0] data_in_b_hh;
wire [35:0] data_out_b_hh;
wire        enable_b;
wire        clk_b;
wire  [3:0] we_b;
//
//
assign address_a = {address[10:0], 3'b000};
assign data_in_a = 36'b000000000000000000000000000000000000;
//
FD s6_a11_flop ( .D      (address[11]),
                 .Q      (pipe_a11),
                 .C      (clk));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux0_lut( .I0     (data_out_a_ll[0]),
                 .I1     (data_out_a_hl[0]),
                 .I2     (data_out_a_ll[1]),
                 .I3     (data_out_a_hl[1]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[0]),
                 .O6     (instruction[1]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux2_lut( .I0     (data_out_a_ll[2]),
                 .I1     (data_out_a_hl[2]),
                 .I2     (data_out_a_ll[3]),
                 .I3     (data_out_a_hl[3]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[2]),
                 .O6     (instruction[3]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux4_lut( .I0     (data_out_a_ll[4]),
                 .I1     (data_out_a_hl[4]),
                 .I2     (data_out_a_ll[5]),
                 .I3     (data_out_a_hl[5]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[4]),
                 .O6     (instruction[5]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux6_lut( .I0     (data_out_a_ll[6]),
                 .I1     (data_out_a_hl[6]),
                 .I2     (data_out_a_ll[7]),
                 .I3     (data_out_a_hl[7]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[6]),
                 .O6     (instruction[7]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
 s6_4k_mux8_lut( .I0     (data_out_a_ll[32]),
                 .I1     (data_out_a_hl[32]),
                 .I2     (data_out_a_lh[0]),
                 .I3     (data_out_a_hh[0]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[8]),
                 .O6     (instruction[9]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux10_lut( .I0     (data_out_a_lh[1]),
                 .I1     (data_out_a_hh[1]),
                 .I2     (data_out_a_lh[2]),
                 .I3     (data_out_a_hh[2]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[10]),
                 .O6     (instruction[11]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux12_lut( .I0     (data_out_a_lh[3]),
                 .I1     (data_out_a_hh[3]),
                 .I2     (data_out_a_lh[4]),
                 .I3     (data_out_a_hh[4]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[12]),
                 .O6     (instruction[13]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux14_lut( .I0     (data_out_a_lh[5]),
                 .I1     (data_out_a_hh[5]),
                 .I2     (data_out_a_lh[6]),
                 .I3     (data_out_a_hh[6]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[14]),
                 .O6     (instruction[15]));
//
LUT6_2 # (       .INIT   (64'hFF00F0F0CCCCAAAA))
s6_4k_mux16_lut( .I0     (data_out_a_lh[7]),
                 .I1     (data_out_a_hh[7]),
                 .I2     (data_out_a_lh[32]),
                 .I3     (data_out_a_hh[32]),
                 .I4     (pipe_a11),
                 .I5     (1'b1),
                 .O5     (instruction[16]),
                 .O6     (instruction[17]));
//
assign address_b = 14'b00000000000000;
assign data_in_b_ll = {3'h0, data_out_b_ll[32], 24'b000000000000000000000000, data_out_b_ll[7:0]};
assign data_in_b_lh = {3'h0, data_out_b_lh[32], 24'b000000000000000000000000, data_out_b_lh[7:0]};
assign data_in_b_hl = {3'h0, data_out_b_hl[32], 24'b000000000000000000000000, data_out_b_hl[7:0]};
assign data_in_b_hh = {3'h0, data_out_b_hh[32], 24'b000000000000000000000000, data_out_b_hh[7:0]};
assign enable_b = 1'b0;
assign we_b = 4'b0000;
assign clk_b = 1'b0;
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F601F00200),
               .INIT_01             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_02             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_03             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_04             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_05             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_06             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_07             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_08             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_09             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0A             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0B             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0C             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0D             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0E             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_0F             (256'hF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_10             (256'h03030303008500000300FFF6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6F6),
               .INIT_11             (256'hF60361F60320F60379F60361F6036CF60350F6030C0303030303030303030303),
               .INIT_12             (256'hFB00F60320F6033AF60365F60367F60361F60373F60373F60365F6034DF60320),
               .INIT_13             (256'h0085F60345F60353F60355F60341F60350F6030DF6030AF6070404030102FE01),
               .INIT_14             (256'h030303030303030303030301850100858201180091017F01090A00D40000850C),
               .INIT_15             (256'h65F6034DF60320F60361F60320F60379F60361F6036CF60350F6030C03030303),
               .INIT_16             (256'h0404030102FE01FB00F60320F6033AF60365F60367F60361F60373F60373F603),
               .INIT_17             (256'h010085F60347F6034EF60349F60359F60341F6034CF60350F6030DF6030AF607),
               .INIT_18             (256'hF6034FF60344F60320F60345F60347F60341F60353F60353F60345F6034D01A2),
               .INIT_19             (256'h0354F60353F60349F60358F60345F60320F60354F60327F6034EF60353F60345),
               .INIT_1A             (256'h0344F60320F60345F60347F60341F60353F60353F60345F6034D01860100A2F6),
               .INIT_1B             (256'h53F60349F60358F60345F60320F60354F60327F6034EF60353F60345F6034FF6),
               .INIT_1C             (256'h0400D431000100D4310000D431000100860B01008501FE000B0086F60354F603),
               .INIT_1D             (256'hF60345F6034DA20B01C001008C01009505009000009EFF99000908070600D431),
               .INIT_1E             (256'h030DF6030AF6034CF6034CF60355F60346F60320F60359F60352F6034FF6034D),
               .INIT_1F             (256'h4CF60341F60320F60345F60347F60341F60353F60353F60345F6034D010031F6),
               .INIT_20             (256'hF60353F60349F60358F60345F60320F60359F60344F60341F60345F60352F603),
               .INIT_21             (256'h0100270031010C030303005005000050E201BA010B0C05010031F60353F60354),
               .INIT_22             (256'h010043043E004CFF47000C090807060028310400283100010028310000283100),
               .INIT_23             (256'h000100003100000031000100690142000B00640C0B0300648B010F00503501C0),
               .INIT_24             (256'h06008B0B04860B03C0016E01007904740082FF7D000908070600003104000031),
               .INIT_25             (256'h6F3114006F3100006F31040101006F31040102009EC00B0401009B01C0010907),
               .INIT_26             (256'h030303030303030303030303C00B050400C00100B815AC00BCFFB20009070600),
               .INIT_27             (256'h0365F6034DF60320F60361F60320F60379F60361F6036CF60350F6030C030303),
               .INIT_28             (256'h070404030102FE01FB00F60320F6033AF60365F60367F60361F60373F60373F6),
               .INIT_29             (256'h65F60352F6030C0B02030303030303030303030303030303A2F6030DF6030AF6),
               .INIT_2A             (256'hF60373F60365F6034DF60320F60361F60320F60364F60372F6036FF60363F603),
               .INIT_2B             (256'h0345F6034CF60345F60353F6030DF6030AF6033FF60365F60367F60361F60373),
               .INIT_2C             (256'h52F60320F6036FF60354F60320F6034EF60354F60342F60320F60354F60343F6),
               .INIT_2D             (256'hF6036CF60369F60346F6030DF6030AF60364F60372F6036FF60363F60365F603),
               .INIT_2E             (256'h036CF60365F60344F6030C50F6070404030102FE01FB00F60320F6033AF60365),
               .INIT_2F             (256'h9EF6030DF6030AF6033FF6036CF6036CF60341F60320F60365F60374F60365F6),
               .INIT_30             (256'h0374F60365F6036CF60365F60344F6030C030303030303030303030303030303),
               .INIT_31             (256'h65F60367F60361F60373F60373F60365F6034DF60320F60361F60320F60365F6),
               .INIT_32             (256'h01FB00F60320F6033AF60365F6036CF60369F60346F6030DF6030AF6033FF603),
               .INIT_33             (256'h030C03030303030303030303030303030386F6030DF6030AF6070404030102FE),
               .INIT_34             (256'h030102FE01FB00F60320F6033AF60365F6036DF60375F6036CF6036FF60356F6),
               .INIT_35             (256'hC000F6030DF6030AF6340E2E0D280C220B1C0A1609130810070D060A05070404),
               .INIT_36             (256'h008B3101008B3100008B3101006F04D50300022801D4000090F6030C008B0B00),
               .INIT_37             (256'h033200033100F6010500E3C30100D7FF00D30000DF0500DB00080706008B3104),
               .INIT_38             (256'h31F60331000330F6033100033900033800033700033600033500033400033300),
               .INIT_39             (256'h03038B010800000335F60331000334F60331000333F60331000332F603310003),
               .INIT_3A             (256'h080303030303030303030303030303038B010803030303030303030303030303),
               .INIT_3B             (256'h0303030303030303030303038B01080303030303030303030303030303038B01),
               .INIT_3C             (256'h03030303030303038B01080303030303030303030303030303038B0108030303),
               .INIT_3D             (256'h030303038B01080303030303030303030303030303038B010803030303030303),
               .INIT_3E             (256'h8B01080303030303030303030303030303038B01080303030303030303030303),
               .INIT_3F             (256'h63F6036CF60365F6035769010CF6030C8B030303030303030303030303030303),
               .INITP_00            (256'h000000000000000000000000000000000000000000000000000000000000000D),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h00000001FA8000000000000000144489000000FD40000000000000000A200000),
               .INITP_03            (256'h00000000000000000229A7D194CA800000000000000000020000000000000001),
               .INITP_04            (256'h00000000000180144469A00500422D194CA210009154ED768200E80000000000),
               .INITP_05            (256'h000000000007EA000000000000000000000000000000000000000080FD400000),
               .INITP_06            (256'h018104A33331110040555555400000000000007EA00000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_ll( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_ll[31:0]),
               .DOPA                (data_out_a_ll[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_ll[31:0]),
               .DOPB                (data_out_b_ll[35:32]), 
               .DIB                 (data_in_b_ll[31:0]),
               .DIPB                (data_in_b_ll[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h030303030303030303030303030303030303030303030303030303038D130D0C),
               .INIT_01             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_02             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_03             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_04             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_05             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_06             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_07             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_08             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_09             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0A             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0B             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0C             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0D             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0E             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_0F             (256'h0303030303030303030303030303030303030303030303030303030303030303),
               .INIT_10             (256'h000000000A91EA001088ED030303030303030303030303030303030303030303),
               .INIT_11             (256'h0368080368080368080368080368080368080368080000000000000000000000),
               .INIT_12             (256'h83EC036808036808036808036808036808036808036808036808036808036808),
               .INIT_13             (256'h00110368080368080368080368080368080368080368080383EC83EC83EC83EC),
               .INIT_14             (256'h00000000000000000000000A91EA001191E891E8B1EA91E8484800120A00116C),
               .INIT_15             (256'h0803680803680803680803680803680803680803680803680803680800000000),
               .INIT_16             (256'hEC83EC83EC83EC83EC0368080368080368080368080368080368080368080368),
               .INIT_17             (256'hEB00110368080368080368080368080368080368080368080368080368080383),
               .INIT_18             (256'h0368080368080368080368080368080368080368080368080368080368080B91),
               .INIT_19             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1A             (256'h68080368080368080368080368080368080368080368080368080B92EB001103),
               .INIT_1B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_1C             (256'h0C00B2EC0BCC00B2EC0C00B2EC0B8C001168080091E891E84800120368080368),
               .INIT_1D             (256'h03680803680811680893E90091E90091EC00A1E80091ECA1E84949484800B2EC),
               .INIT_1E             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_1F             (256'h080368080368080368080368080368080368080368080368080368080B001203),
               .INIT_20             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_21             (256'h8C0092EC92EC6C00000000126808001291E991EA494A68080012036808036808),
               .INIT_22             (256'hE90092ECA2E892ECA2E84A4949484800B2EC0C00B2EC0BCC00B2EC0C00B2EC0B),
               .INIT_23             (256'h0BCC00B3EC0C00B3EC0B8C0092E891E84800126C6808001294E848001292E993),
               .INIT_24             (256'h480014680812680893E992E90092ECA2E892ECA2E84949484800B3EC0C00B3EC),
               .INIT_25             (256'hB3EC0D00B3EC0D00B3EC6F8D0F00B3EC6FCD0F0012936808E90082E893E84948),
               .INIT_26             (256'h0000000000000000000000001268086B0B93E90092EDA2E892EDA2E849484800),
               .INIT_27             (256'h6808036808036808036808036808036808036808036808036808036808000000),
               .INIT_28             (256'h83EC83EC83EC83EC83EC03680803680803680803680803680803680803680803),
               .INIT_29             (256'h0803680803680868080000000000000000000000000000001103680803680803),
               .INIT_2A             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2B             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_2C             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_2D             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_2E             (256'h6808036808036808036808120383EC83EC83EC83EC83EC036808036808036808),
               .INIT_2F             (256'h1203680803680803680803680803680803680803680803680803680803680803),
               .INIT_30             (256'h6808036808036808036808036808036808000000000000000000000000000000),
               .INIT_31             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_32             (256'hEC83EC0368080368080368080368080368080368080368080368080368080368),
               .INIT_33             (256'h6808000000000000000000000000000000120368080368080383EC83EC83EC83),
               .INIT_34             (256'hED83ED83ED83ED03680803680803680803680803680803680803680803680803),
               .INIT_35             (256'h120D0368080368080383ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83ED83),
               .INIT_36             (256'h00B4ECCC00B4EC0C00B4EC8C0093E892E893E892E892E80C0003680800146808),
               .INIT_37             (256'h68082868082893E949001393E90093EC00A3E80093EC00A3E849484800B4EC0C),
               .INIT_38             (256'h0803680828680803680828680828680828680828680828680828680828680828),
               .INIT_39             (256'h000094E848002868080368082868080368082868080368082868080368082868),
               .INIT_3A             (256'h4800000000000000000000000000000094E84800000000000000000000000000),
               .INIT_3B             (256'h00000000000000000000000094E84800000000000000000000000000000094E8),
               .INIT_3C             (256'h000000000000000094E84800000000000000000000000000000094E848000000),
               .INIT_3D             (256'h0000000094E84800000000000000000000000000000094E84800000000000000),
               .INIT_3E             (256'h94E84800000000000000000000000000000094E8480000000000000000000000),
               .INIT_3F             (256'h0803680803680803680884E80803680814000000000000000000000000000000),
               .INITP_00            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4),
               .INITP_01            (256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF),
               .INITP_02            (256'h3B6DB6DB556DB6DB6DB6DB6FFFE9AA1376DB6DAAB6DB6DB6DB6DB7FFF4DFFFFF),
               .INITP_03            (256'h6DB6DB63B6DB6DB6DB4925022110CA3B6DB6DB6DB6DB6D93B6DB6DB6DB6DB6D9),
               .INITP_04            (256'hB6DB6DB7FFFD4AA088A28E2836A55022110A398D2A8088442BD9A276DB6DB6DB),
               .INITP_05            (256'hEDB6DB6DB6DD55B6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D7FFFEDAAB6DB6D),
               .INITP_06            (256'hB632490444455466B6D5555555B6DB6DBFFFF6D55B6DB6DB6DB6DB6DB6DB7FFF),
               .INITP_07            (256'h6DA6FFFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE7FFF9FFFE36DB6DB6DB6DB6D))
kcpsm6_rom_lh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_lh[31:0]),
               .DOPA                (data_out_a_lh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_lh[31:0]),
               .DOPB                (data_out_b_lh[35:32]), 
               .DIB                 (data_in_b_lh[31:0]),
               .DIPB                (data_in_b_lh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'hF60364F60365F6034DF60320F6036FF60374F60320F60365F6036DF6036FF603),
               .INIT_01             (256'h0365F60356F60320F60372F60365F60379F60361F6036CF60370F60361F60369),
               .INIT_02             (256'h2EF60330F60332F6032EF60334F60320F6036EF6036FF60369F60373F60372F6),
               .INIT_03             (256'h0346F60320F60359F60352F6034FF6034DF60345F6034D3AF60339F60336F603),
               .INIT_04             (256'h0361F60369F60364F60365F6034D69010CF6030C0000F6034CF6034CF60355F6),
               .INIT_05             (256'h73F60372F60365F60356F60320F60372F60365F60379F60361F6036CF60370F6),
               .INIT_06             (256'hF60336F6032EF60330F60332F6032EF60334F60320F6036EF6036FF60369F603),
               .INIT_07             (256'h0374F60370F6034FF60320F60375F6036EF60365F6034DF6030DF6030AF60339),
               .INIT_08             (256'h20F60329F6032EF60331F6030DF6030AF6033AF60373F6036EF6036FF60369F6),
               .INIT_09             (256'hF60373F60365F6034DF60320F60361F60320F60379F60361F6036CF60350F603),
               .INIT_0A             (256'h0352F60320F60329F6032EF60332F6030DF6030AF60365F60367F60361F60373),
               .INIT_0B             (256'h73F60365F6034DF60320F60361F60320F60364F60372F6036FF60363F60365F6),
               .INIT_0C             (256'hF60320F60329F6032EF60333F6030DF6030AF60365F60367F60361F60373F603),
               .INIT_0D             (256'h0365F6034DF60320F60361F60320F60365F60374F60365F6036CF60365F60344),
               .INIT_0E             (256'h20F60329F6032EF60334F6030DF6030AF60365F60367F60361F60373F60373F6),
               .INIT_0F             (256'hF6036CF6036CF60361F60320F60365F60374F60365F6036CF60365F60344F603),
               .INIT_10             (256'h030DF6030AF60373F60365F60367F60361F60373F60373F60365F6034DF60320),
               .INIT_11             (256'h20F60365F6036DF60375F6036CF6036FF60356F60320F60329F6032EF60335F6),
               .INIT_12             (256'hF60343F6030DF6030AF6036CF6036FF60372F60374F6036EF6036FF60343F603),
               .INIT_13             (256'h0365F6036CF60365F60353F60320F60374F6036EF60365F60372F60372F60375),
               .INIT_14             (256'h070404030102FE01FB00F60320F6033AF6036EF6036FF60369F60374F60363F6),
               .INIT_15             (256'h000000000000000000000000000000000000000000000000E3F6030DF6030AF6),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h0000000000000000000000000000000000000100000000000000000000000000),
               .INITP_01            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_02            (256'h000000000000000000000000FD40000000000000000000000000000000000000),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hl( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hl[31:0]),
               .DOPA                (data_out_a_hl[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hl[31:0]),
               .DOPB                (data_out_b_hl[35:32]), 
               .DIB                 (data_in_b_hl[31:0]),
               .DIPB                (data_in_b_hl[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
RAMB16BWER # ( .DATA_WIDTH_A        (9),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (9),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_01             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_02             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_03             (256'h6808036808036808036808036808036808036808036808130368080368080368),
               .INIT_04             (256'h680803680803680803680803680884E808036808002803680803680803680803),
               .INIT_05             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_06             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_07             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_08             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_09             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0A             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0B             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0C             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_0D             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_0E             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_0F             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_10             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_11             (256'h0803680803680803680803680803680803680803680803680803680803680803),
               .INIT_12             (256'h0368080368080368080368080368080368080368080368080368080368080368),
               .INIT_13             (256'h6808036808036808036808036808036808036808036808036808036808036808),
               .INIT_14             (256'h83EC83EC83EC83EC83EC03680803680803680803680803680803680803680803),
               .INIT_15             (256'h0000000000000000000000000000000000000000000000001303680803680803),
               .INIT_16             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_17             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_18             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_19             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_1F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_31             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'hB6DB6DB6DB6DB6DB6DB6DB6DB6DA676DB6DB6DDB6DB6DB6DB6DB6DB6DB6DB6DB),
               .INITP_01            (256'hDB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6D),
               .INITP_02            (256'h0000000000000000000000EDAAB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6DB6),
               .INITP_03            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
kcpsm6_rom_hh( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a_hh[31:0]),
               .DOPA                (data_out_a_hh[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b_hh[31:0]),
               .DOPB                (data_out_b_hh[35:32]), 
               .DIB                 (data_in_b_hh[31:0]),
               .DIPB                (data_in_b_hh[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE program.v
//
////////////////////////////////////////////////////////////////////////////////////
